model_path:
  small: "./mistral-7b-instruct-v0.1.Q4_K_M.gguf"

model_type: "mistral"

embeddings_path: "BAAI/bge-large-en-v1.5"

model_config: {'max_new-tokens': 512, 'tempreture': 0, 'context_length': 4096, 'gpu_layer': 0}